version: "3.6"

services:
  web:
    build: .
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    ports:
      - "4000:4000"
    links:
      - "db"
    depends_on:
      - "db"
    networks: 
      - "chat"

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat
    ports:
      - "5432:5432"
    networks: 
      - "chat"

networks: 
  chat: